"""empty message

Revision ID: 041efac97707
Revises: 0c804d55ef18
Create Date: 2017-05-31 17:15:16.877989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041efac97707'
down_revision = '0c804d55ef18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chars', sa.Column('ring_1', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chars', 'ring_1')
    # ### end Alembic commands ###
