"""empty message

Revision ID: 0c804d55ef18
Revises: a7429e034187
Create Date: 2017-05-31 17:12:03.475922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c804d55ef18'
down_revision = 'a7429e034187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chars', sa.Column('race_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chars', 'races', ['race_id'], ['id'])
    op.drop_column('chars', 'race')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chars', sa.Column('race', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chars', type_='foreignkey')
    op.drop_column('chars', 'race_id')
    # ### end Alembic commands ###
