"""empty message

Revision ID: a7429e034187
Revises: 7d98fc5ca203
Create Date: 2017-05-31 17:06:38.912225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7429e034187'
down_revision = '7d98fc5ca203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chars', sa.Column('AC', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('AC_flatfooted', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('AC_natural', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('AC_touch', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('BAB', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('SAVE_for', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('SAVE_ref', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('SAVE_will', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('armor', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('cha', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('con', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('description', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('dex', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('foot_protection', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('hand_protection', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('head_protection', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('initiative', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('int', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('klass', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('left_hand', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('magic_resist', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('player_name', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('race', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('right_hand', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('shield', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('speed', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('str', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('wis', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chars', 'wis')
    op.drop_column('chars', 'str')
    op.drop_column('chars', 'speed')
    op.drop_column('chars', 'size')
    op.drop_column('chars', 'shield')
    op.drop_column('chars', 'right_hand')
    op.drop_column('chars', 'race')
    op.drop_column('chars', 'player_name')
    op.drop_column('chars', 'magic_resist')
    op.drop_column('chars', 'level')
    op.drop_column('chars', 'left_hand')
    op.drop_column('chars', 'klass')
    op.drop_column('chars', 'int')
    op.drop_column('chars', 'initiative')
    op.drop_column('chars', 'head_protection')
    op.drop_column('chars', 'hand_protection')
    op.drop_column('chars', 'foot_protection')
    op.drop_column('chars', 'dex')
    op.drop_column('chars', 'description')
    op.drop_column('chars', 'con')
    op.drop_column('chars', 'cha')
    op.drop_column('chars', 'armor')
    op.drop_column('chars', 'SAVE_will')
    op.drop_column('chars', 'SAVE_ref')
    op.drop_column('chars', 'SAVE_for')
    op.drop_column('chars', 'BAB')
    op.drop_column('chars', 'AC_touch')
    op.drop_column('chars', 'AC_natural')
    op.drop_column('chars', 'AC_flatfooted')
    op.drop_column('chars', 'AC')
    op.drop_table('races')
    # ### end Alembic commands ###
