"""empty message

Revision ID: e33e35127292
Revises: 041efac97707
Create Date: 2017-06-01 10:03:59.640362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33e35127292'
down_revision = '041efac97707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chars', sa.Column('klass_id', sa.Integer(), nullable=True))
    op.add_column('chars', sa.Column('left_hand_1', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('left_hand_2', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('right_hand_1', sa.String(), nullable=True))
    op.add_column('chars', sa.Column('right_hand_2', sa.String(), nullable=True))
    op.create_foreign_key(None, 'chars', 'classes', ['klass_id'], ['id'])
    op.create_foreign_key(None, 'chars', 'races', ['race_id'], ['id'])
    op.drop_column('chars', 'foot_protection')
    op.drop_column('chars', 'left_hand')
    op.drop_column('chars', 'klass')
    op.drop_column('chars', 'ring_1')
    op.drop_column('chars', 'right_hand')
    op.add_column('classes', sa.Column('description', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('name', sa.String(), nullable=True))
    op.add_column('races', sa.Column('description', sa.String(), nullable=True))
    op.add_column('races', sa.Column('name', sa.String(), nullable=True))
    op.add_column('races', sa.Column('size', sa.String(), nullable=True))
    op.add_column('weapons', sa.Column('cost', sa.String(), nullable=True))
    op.add_column('weapons', sa.Column('critical', sa.Integer(), nullable=True))
    op.add_column('weapons', sa.Column('description', sa.String(), nullable=True))
    op.add_column('weapons', sa.Column('dmg_M', sa.String(), nullable=True))
    op.add_column('weapons', sa.Column('dmg_S', sa.String(), nullable=True))
    op.add_column('weapons', sa.Column('dmg_type', sa.String(), nullable=True))
    op.add_column('weapons', sa.Column('name', sa.String(), nullable=True))
    op.add_column('weapons', sa.Column('range_increment', sa.Integer(), nullable=True))
    op.add_column('weapons', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapons', 'weight')
    op.drop_column('weapons', 'range_increment')
    op.drop_column('weapons', 'name')
    op.drop_column('weapons', 'dmg_type')
    op.drop_column('weapons', 'dmg_S')
    op.drop_column('weapons', 'dmg_M')
    op.drop_column('weapons', 'description')
    op.drop_column('weapons', 'critical')
    op.drop_column('weapons', 'cost')
    op.drop_column('races', 'size')
    op.drop_column('races', 'name')
    op.drop_column('races', 'description')
    op.drop_column('classes', 'name')
    op.drop_column('classes', 'description')
    op.add_column('chars', sa.Column('right_hand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chars', sa.Column('ring_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chars', sa.Column('klass', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chars', sa.Column('left_hand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chars', sa.Column('foot_protection', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chars', type_='foreignkey')
    op.drop_constraint(None, 'chars', type_='foreignkey')
    op.drop_column('chars', 'right_hand_2')
    op.drop_column('chars', 'right_hand_1')
    op.drop_column('chars', 'left_hand_2')
    op.drop_column('chars', 'left_hand_1')
    op.drop_column('chars', 'klass_id')
    # ### end Alembic commands ###
